manifest:
  self:
    path: smarthome-openthread-mqttsn

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.1
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nordic
          - mbedtls
          - mcuboot
          - openthread
          - segger
          - tf-psa-crypto
          - zcbor
