CONFIG_POLL=y
CONFIG_RING_BUFFER=y
CONFIG_UART_ASYNC_API=y
CONFIG_REBOOT=y
CONFIG_SERIAL=y

CONFIG_SMARTHOME_RUST=y
CONFIG_SMARTHOME_MQTTSN_DEVICE=y

CONFIG_COMPILER_OPT="-Werror"
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_PICOLIBC_IO_FLOAT=y

CONFIG_OPENTHREAD_MTD=y
CONFIG_OPENTHREAD_MTD_SED=y
CONFIG_OPENTHREAD_FTD=n
CONFIG_OPENTHREAD_DEFAULT_TX_POWER=8

# MQTT-SN
CONFIG_MQTT_SN_LIB=y
CONFIG_MQTT_SN_TRANSPORT_UDP=y
CONFIG_SMARTHOME_MQTTSN_DEVICE=y

CONFIG_OPENTHREAD_POLL_PERIOD=60000
CONFIG_SMARTHOME_MQTTSN_DEVICE_RECONNECT_WAIT_DURATION=61
CONFIG_MQTT_SN_LIB_T_RETRY=61
CONFIG_MQTT_SN_KEEPALIVE=60
